version: '3.6'

services:
  #postgres database
  postgres:
    container_name: postgres
    build: ./src/configs/postgres
    environment:
      POSTGRES_DB: FCC
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"

  #Redis session database
  redis:
    container_name: redis
    image: redis:5.0.3
    ports:
      - "6379:6379"
    
  #expres.js backend server
  backend:
    container_name: express
    build: ./
    command: npm run dev
    ports:
      - "3001:3001"
    # volumes:
    #   - ./:/usr/src/backend
    env_file:
      - .env
    environment:
      DB_HOST: postgres #overwrite DB_HOST in .env (only for Docker)
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
